- ""
- description
- composed
- source
- world-premiere
- n.b.
- libretto
- durata
- synopsis
- cast
- ursetting
- reworking
- setting
- publication
- text
- subject
- choregraphy
- parts
- publication-n.b.
- dedicated
- source-reworking
- publication-reworking
- adapted
- other-titles
- publication-in
- recording
- deicated
- publication-source
- n.b
- part
- subtitle
- source-publication
- score
- 25-film-scores-written-for-short-films-relating-to-shipments-to-madagascar-and-the-seychelles-islands
- men-and-banners
- a-magyar-falu-mosolya-short-film
- a-magyar-lo-short-film
- autoval-a-karpataljan-short-film
- az-eger-es-az-oroszlan-short-film
- baromfitenyesztes-magyarorszagon-short-film
- csinom-palko
- the-lost-talisman
- ref-fn-al-tt-1-short-film-documentary-film
- fueggetlensegi-harcaink-a-kepzoemueveszetben-documentary-film
- -documentary-film
- itel-a-puszta-short-film
- -short-film-documentary-film
- magyar-vad-short-film
- megindul-az-erdoe-short-film
- ref-fn-al-tt-1
- ref-fn-al-tt-1-documentary-film
- vas-es-gepipar-short-film
- literal-translation-of-the-title
- film-director
- film-producer
- viharsarok-documentary-film
