baseURL = "/"
languageCode = "en-us"
title = "Ferenc Farkas - A european composer"
enableRobotsTXT = true
disableAliases = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
disallow_search_engines = false # set robots.txt to disallow everything
description = "Ferenc Farkas official website."

  [params.og]
  image = "/img/og-image.jpg"

[menu]

  [[menu.main]]
  name = "Biography"
  identifier = "biography"
  weight = 100.0
  url = "/biography"

  [[menu.main]]
  name = "Work"
  identifier = "work"
  weight = 200.0
  url = "/work"

  # [[menu.main]]
  # name = "Discover"
  # identifier = "discover"
  # weight = 300.0
  # url = "/discover"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 400.0
  url = "/contact"

[outputFormats]

  [outputFormats.JSON]
  mediaType = "application/json"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true